[package]
name = "ctf-tools"
version = "0.1.0"
authors = ["Riko <xxy1836@gmail.com>"]
edition = "2021"

[dependencies]
iced = { path = "./iced" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
iced = { path = "./iced", features = ["webgl"] }